### PR TITLE
Manager to search items today and tomorrow

### PR DESCRIPTION
**Pull request by gilsondev**
I'm created a manager to search items that scheduled to today and
tomorrow. I use `api.query` to this. Feedback is welcome ;)

### CODE REVIEW

**Comment by eleftherios-c** [comment]
Thanks for you contribution!

The problem is that the query functionality is at the moment broken, and that's why instead of one element in the list you get back from the server, you get multiple.  We have removed it from the documentation, and we will remove it also from our python module, as it is surely confusing.

We are working on providing a uniform filtering solution, across all our clients, and of course our server and public API.

**Comment by eleftherios-c** [comment]
I think I found out why it didn't work properly for you, you actually have to use `api.query(['tomorrow'])` or `api.query(['today'])`.  Let me see if we can have this included for now...

**Comment by tomasrollo** [comment]
Hi, is there a timeplan on fixing the query api method (to support also non-date queries)? Currently when I'm trying to search for a non-date string (e.g. `api.query(['example_string'])`) I'm still getting multiple lists and not relevant tasks.

Thanks
T.

**Comment by lefcha** [comment]
Unfortunately, our plans for releasing a new and advanced query/search function, have been on hold for now.  Hopefully we can have some better news soon.

**Pull request closed without merging**
